apiVersion : apps/v1
kind: Deployment
metadata:
  name : web
  labels:
    app : myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      project: projectborealis
  template:
    metadata:
      labels:
        project: projectborealis # Service will look for those PODs labels!!!
    spec:
      containers:
        - name : httpds
          image: httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 2
  maxReplicas: 6
  metrics    :
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: myhttpd
    env: prod
    owner: PavelKhoroshilov
spec:
  selector: # Selecting PODs with those labes
    project: projectborealis
  ports:
    - name: app-listener
      protocol : TCP
      port : 80 # Port on LoadBalancer
      targetPort: 80 # Port on POD
  type: LoadBalancer
